### ISSUE TITLE
const [renderedList, setRenderedList] = useState(StudentsData);

### ISSUE THREAD

**Issue by dennisXZX** [ZoeZhanZY/react-student-scores#2]
https://github.com/ZoeZhanZY/react-student-scores/blob/208d8be3a7afed092b274f196b1704860c0e1609/src/components/App.js#L7

Can directly use StudentSData

const [renderedList, setRenderedList] = useState(StudentsData);

**Comment by ZoeZhanZY** [comment]
Solved
