### ISSUE TITLE
renderedList should not be passed to this component

### ISSUE THREAD

**Issue by dennisXZX** [ZoeZhanZY/react-student-scores#3]
https://github.com/ZoeZhanZY/react-student-scores/blob/208d8be3a7afed092b274f196b1704860c0e1609/src/components/App.js#L22

renderedList should not be passed to this component, bcuz it would cause unnecessary re-renders. We should pass a callback handle to Sort component.

**Comment by ZoeZhanZY** [comment]
issue solved
