### ISSUE TITLE
convention is to use kebab-case in CSS styling

### ISSUE THREAD

**Issue by dennisXZX** [ZoeZhanZY/react-student-scores#5]
https://github.com/ZoeZhanZY/react-student-scores/blob/208d8be3a7afed092b274f196b1704860c0e1609/src/components/Filter/Filter.module.css#L2

filterCell -> filter-cell

We do not use camel case in CSS, camel case is for JS, CSS will use kebab case.

**Comment by ZoeZhanZY** [comment]
issue resolved.
